#!/bin/bash
#SBATCH --output HPCProject_%j_output.txt
#SBATCH --error HPCProject_%j_error.txt
#SBATCH --mail-user leonardo.barzon.1@studenti.unipd.it
#SBATCH --mail-type ALL
#SBATCH
#SBATCH --time 0-06:00:00
#SBATCH --ntasks 1
#SBATCH -c 1
#SBATCH --partition allgroups
#SBATCH --mem 8G
#SBATCH --exclude=gpu[1-3]

newgrp biopetmri_tesi

srun singularity exec HPC_Singularity.sif python3 /HPC/HPC_project/MAIN_Network_Analysis_PBR.py